# name: CI Symfony

# on:
#   push:
#     branches: [main, develop]
#   pull_request:
#     branches: [main, develop]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     services:
#       postgres:
#         image: postgres:16
#         env:
#           POSTGRES_USER: postgres
#           POSTGRES_PASSWORD: postgres
#           POSTGRES_DB: ina_zaoui_test
#         ports:
#           - 5432:5432
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5

#     env:
#       DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/ina_zaoui_test?serverVersion=16&charset=utf8"

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Setup PHP
#       uses: shivammathur/setup-php@v2
#       with:
#         php-version: '8.2'
#         extensions: mbstring, intl, pdo_pgsql, xml, zip

#     - name: Install Composer dependencies
#       run: composer install --no-progress --prefer-dist --optimize-autoloader

#     - name: Wait for PostgreSQL
#       run: |
#         until pg_isready -h localhost -p 5432 -U postgres -d ina_zaoui_test; do
#         echo "Waiting for PostgreSQL..."
#         sleep 1
#         done

#     - name: Create test database
#       run: php bin/console doctrine:database:create --env=test

#     - name: Import backup SQL
#       run: |
#         psql postgresql://postgres:postgres@localhost:5432/ina_zaoui_test -f backup/backup.sql

#     - name: Run PHPUnit tests
#       run: php bin/phpunit --coverage-text

name: CI Symfony

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ina_zaoui_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/ina_zaoui_test?serverVersion=16&charset=utf8"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, intl, pdo_pgsql, xml, zip

    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Wait for PostgreSQL
      run: |
        until pg_isready -h localhost -p 5432 -U postgres -d ina_zaoui_test; do
          echo "Waiting for PostgreSQL..."
          sleep 1
        done

    - name: Create test database manually
      run: |
          PGPASSWORD=postgres psql -h 127.0.0.1 -U postgres -c 'CREATE DATABASE "ina_zaoui_test_test";'

    - name: Run Doctrine schema update
      run: php bin/console doctrine:schema:create --env=test

    - name: Load test fixtures
      run: php bin/console doctrine:fixtures:load --group=test --no-interaction --env=test

    - name : Run PHPStan
      run: vendor/bin/phpstan analyse --no-progress --error-format=table

    - name: Run PHPUnit tests
      run: php bin/phpunit --coverage-text
